### ISSUE TITLE
Text is unreadable on white backgrounds

### ISSUE THREAD

**Issue by mattlyons0** [owenthewizard/i3lock-next#1]
For my old locker script using GraphicsMagick I was sampling for the overall average brightness of the images on the screen (by converting an image to a 1x1 hsb colorspace) and taking anything from below 40% to show white text or above 40% to show black text. I even went further to change the lock image to a dark version on white backgrounds.

Currently with your implementation the text is always white.
I'd be interesting to see a implementation of something like this in the library you use (and how the performance is). In GM it takes a second or so.

**Comment by owenthewizard** [comment]
I am aware of this issue and looking into it.
