### ISSUE TITLE
Does it really require fontconfig?

### ISSUE THREAD

**Issue by crocket** [owenthewizard/i3lock-next#25]
fontconfig is not a build-time dependency. I don't know whether it is a run-time dependency.

**Comment by crocket** [comment]
Oh, i3lock-next uses fc-match which belongs to fontconfig.

**Comment by owenthewizard** [comment]
It is changed from a run-time to a build-time dependency in the rewrite branch.

**Comment by crocket** [comment]
Is bash a run-time dependency, too?

**Comment by owenthewizard** [comment]
In the master branch, Imlib2 and libXrandr are build-time, while fontconfig and ~~~bash~~~ python are run-time. Bash was actually replaced with python in a911378, I forgot to update the README.

In the rewrite branch, Imlib2, libXrandr, and fontconfig are build-time, as well as bash for one script that I'm working on migrating. [yuck](https://github.com/hroptatyr/yuck) is needed to regenerate `i3lock-next.yucc` but is not needed for a release build.
