### ISSUE TITLE
i3lock: invalid option -- 'k'

### ISSUE THREAD

**Issue by turbo2025** [owenthewizard/i3lock-next#26]
after make install the tool , input  i3lock-next  "Input password" "DejaVu Sans Mono" 24  in terminal , the error is below  : 
i3lock: invalid option -- 'k'
i3lock: Syntax: i3lock [-v] [-n] [-b] [-d] [-c color] [-u] [-p win|default] [-i image.png] [-t] [-e]

**Comment by owenthewizard** [comment]
What version of i3lock-color are you using?

**Comment by turbo2025** [comment]
Dependencies tools ,had fixed
