### ISSUE TITLE
Suggestion: create a package release

### ISSUE THREAD

**Issue by sinetoami** [owenthewizard/i3lock-next#28]
Can you create a package release from this repository? Please. Maybe someone desire to create a build package from this repo. So, if you create a release, makes this much better. Thanks :+1:

**Comment by owenthewizard** [comment]
This project isn't very good. I don't plan to maintain or update it in its current state. I should probably just archive it.

**Comment by sinetoami** [comment]
Oh, dude... :( 
I like this plugin. I'm using it because is the only one that works very good(and very fast) on my environment. Any chance to you recreate it in another way?

**Comment by owenthewizard** [comment]
~~I've been playing around with Rust and the image crate. As per PistonDevelopers/image#580 there's no proper way to import an X11 `XImage`. Using the linked function takes \~3 seconds, which is too slow.~~

~~If a faster way was added I could write this in Rust using image.~~

Ignore this

**Comment by sinetoami** [comment]
Sounds good to me. ~3 seconds is more fastest than others plugins with same goals. If you can do this much better using Rust, I'll be very happy to create a Void package from this plugin. Actually, I did a [pull-request](https://github.com/void-linux/void-packages/pull/4737) to void-packages with the latest commit.

**Comment by owenthewizard** [comment]
Alright, I'll work on it. Consider closing void-linux/void-packages#4737.

**Comment by owenthewizard** [comment]
I'm an idiot, I was timing the debug builds without optimizations. The actual time is *MUCH* quicker.

**Comment by sinetoami** [comment]
What optimizations have you made? Are you already working on the Rust version?

**Comment by owenthewizard** [comment]
Just the Rust default `--release` target, which enables `-O3` as opposed to `-O0` in the debug target.

I've been working on a Rust version since I self-assigned this, I didn't want to make it public if it failed.

**Comment by sinetoami** [comment]
> Alright, I'll work on it. Consider closing [void-linux/void-packages#4737](https://github.com/void-linux/void-packages/pull/4737).

It's not necessary to close the PR. When you update this repo(even if you create another), I can update the PR. Don't worry. ;)

> Just the Rust default `--release` target, which enables `-O3` as opposed to `-O0` in the debug target.
> 
> I've been working on a Rust version since I self-assigned this, I didn't want to make it public if it failed.

I still know nothing about programming with Rust yet, but I know about the power behind it. I'm glad you're for working on it. I hope to help you improve this some day. 

Thanks

**Comment by owenthewizard** [comment]
I'm very much a beginner with Rust, but I much prefer it to C. I highly recommend learning it.

I'd say you're already helping because I was just letting this project rot before.

**Comment by owenthewizard** [comment]
@sinetoami
Sorry for the wait, pre-release [here](https://github.com/owenthewizard/i3lockr), with proper versioning.
