### ISSUE TITLE
Fix issue with using fingerprint sensor

### ISSUE THREAD

**Issue by ddnomad** [owenthewizard/i3lock-next#29]
First of all, thank you for this wonderful project. Really liked it and trying to use it now in my setup.

Though I found an "issue" that makes fingerprint sensor usage even more awkward then it was with vanilla `i3lock`. As I can see, you prevent submission of a password with Enter key if there is no characters entered previously. While it makes perfect sense for password login, it causes some issues with fingerprint authentication.

The way `pam_fprintd` works with `i3lock` is that it fires up a fingerprint sensor when the password is submitted -> Enter pressed. And as you block this when password has length 0, I have to type in gibberish each time to press Enter and then finally use a fingerprint sensor.

That's, well, inconvenient. Overall I'd love to see some more civil way of triggering fingerprint sensor though I'm not sure it's possible to do without modifying `i3lock-color` itself.

Any way it can be fixed/improved?

P.S. I can assist you with PKGBUILD if you want, have some experience with them before.

**Comment by owenthewizard** [comment]
All that should be necessary is changing `ignoreempty = Yes` to `ignoreempty = No` in `~/.config/i3lock-next/i3lock-next.ini`.

I'm working on a new version written in Rust, so I'd rather avoid making releases of this version.

**Comment by ddnomad** [comment]
Thank you for the solution! Looking forward to a new version :)
