### ISSUE TITLE
Dots in font path handled incorrectly

### ISSUE THREAD

**Issue by SuprDewd** [owenthewizard/i3lock-next#3]
In my case, the font path that is returned by fc-match (which i3lock-next calls) is:
~~~
/nix/store/vybrixx6cg1ayn7ryby96688y1rsrrx4-dejavu-fonts-2.37/share/fonts/truetype/DejaVuSans.ttf
~~~
Notice that there are two dots in this path, the first one in "2.37". This is handled incorrectly by i3lock-next, as it strips out everything after the first dot:
https://github.com/owenthewizard/i3lock-next/blob/master/scripts/i3lock-next#L29

It seems like there is already a proposed fix, namely on line 30 in the same file. I tried using that (and removing the `cut` on line 29), and then it seems to work correctly.

**Comment by owenthewizard** [comment]
The issue should be fixed now, please test the latest commit.
