### ISSUE TITLE
Use configured PREFIX throughout

### ISSUE THREAD

**Issue by SuprDewd** [owenthewizard/i3lock-next#4]
When doing a `make install` with a custom PREFIX, both `i3lock-next` and `i3lock-next-helper` should respect that prefix. (Currently they both seem to be practically hardcoded to /usr/local). These are just suggestions, but:

- To fix `i3lock-next-helper`, add the following to the Makefile:
~~~
CFLAGS += "-DPREFIX=\"$(PREFIX)\" "
~~~

- To fix `i3lock-next`, simply do a sed replace of /usr/local with PREFIX after the file has been installed in the Makefile. This could also be made cleaner by making a specific config.py hold that path.

**Comment by owenthewizard** [comment]
Thank you, should be fixed now.
